name: easy-wg-quick workflow

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    name: sca check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: shellcheck
        uses: ./.github/actions/shellcheck
      - name: checkbashisms
        uses: ./.github/actions/checkbashisms
  test:
    name: test run
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: testrun
        uses: ./.github/actions/testrun
