name: push workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: shellcheck
        uses: ./.github/actions/shellcheck
      - name: checkbashisms
        uses: ./.github/actions/checkbashisms
  test:
    runs-on: ubuntu-latest
    steps:
      - name: testrun
        uses: ./.github/actions/testrun
